name: Сборка проекта при запросе на слияние
on:
  pull_request:
    branches: ["master"]
jobs:
  build-test:
    name: Check build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Compile java files
        run: |
          mkdir -p classes
          javac -d classes $(find ./src -name "*.java")
